version: 0.2

env:
  secrets-manager:
    AWS_ACCOUNT_ID: owebui:AWS_ACCOUNT_ID
    DOCKER_USER: owebui:DOCKER_USER
    DOCKER_PAT: owebui:DOCKER_PAT

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo Setting up the build environment and logging into ECR
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/$ECR_PATH
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
      - docker login --username $DOCKER_USER --password $DOCKER_PAT
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file
      - printf '[{"name":"nemesis","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
